myDjangoProject/myDjangoProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myFirstApp.urls')),
]

myDjangoProject/myFirstApp/urls.py
from django.urls import path

from . import views

app_name = 'myFirstApp'
urlpatterns = [
    # localhost:8000
    path('', views.index, name='index'),

    # localhost:8000/article/id
    path('article/<int:article_id>/', views.article, name='article'),

    # localhost:8000/search/id
    path('search/<str:article_text>/', views.search, name='search'),

    # localhost:8000/archive
    path('archive/', views.archive, name = 'archive'),

    # localhost:8000/article/id/comments_block
    path('article/<int:article_id>/comments_block', views.showComments, name='comments_block')

]

myDjangoProject/myFirstApp/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
	article_name = models.CharField(max_length = 1000)
	article_text = models.TextField()
	article_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.article_name
		
class Editor(models.Model):
	editor_name = models.CharField(max_length = 100)
	editor_surname = models.CharField(max_length = 100)
	
	def __str__(self):
		return self.editor_name + " " + self.editor_surname 
		
class User(models.Model):
	user_name = models.CharField(max_length = 100)
	user_surname = models.CharField(max_length = 100)
	user_dob = models.DateTimeField('date of birth')
	
	def __str__(self):
		return self.user_name + " " + self.user_surname

class Comments(models.Model):
	comments_text = models.TextField()

	def __str__(self):
		return self.comments_text

class Ads(models.Model):
	ads_owner = models.CharField(max_length=100)
	ads_content = models.TextField()
	
	def __str__(self):
		return self.ads_content
		
class QuantityOfViews(models.Model):
	number_of_views = models.IntegerField()
	link_to_hidden_ad = models.TextField()
	
	def getNumberOfViews(self):
		return self.number_of_views

myDjangoProject/myFirstApp/views.py
from django.http import HttpResponse, Http404
from .models import *
# from django.template import loader
from django.shortcuts import render, get_object_or_404


# Create your views here.
def index(request):

    latest_articles = Article.objects.order_by('-article_date')

    """Using render() to laod the template"""
    return render(request, "myFirstApp/index.html", {'latest_articles':latest_articles})

    """Using loader.get_template(context, request)"""
    # template = loader.get_template('myFirstApp/index.html')
    # context = {
    #     'latest_articles':latest_articles,
    # }
    # return HttpResponse(template.render(context,request))

    """Using simple HttpResponse()"""
    # ans = '<br>'.join([a.article_name for a in latest_articles])
    # return HttpResponse(
    # "<center><b><h2> <br><br>More beautiful outpus is coming <br>The list of articles<br> %s <h2></b></center>"%ans
    # )

def article(request, article_id):
    """Using get_object_or_404() shortcut to return PNF 404"""
    art = get_object_or_404(Article, pk=article_id)
    print(type(art), art)
    return render(request, "myFirstApp/article.html", {"article":art})

    # try:
    #     article = Article.objects.get(pk=article_id)
    # except:
        # """using Http404() to raise an exception of page not found"""
        # raise Http404("No such article by id %i" %article_id)

        # """Using simple HttpResponse to say that there is no such article by given id"""
        # return HttpResponse("No Such Article")
    # return HttpResponse("This article’s desciption is %s" % article.article_text)

def search(request, article_text):
    search_res = list(Article.objects.filter(article_text__contains=article_text).values_list("article_text"))
    try:
        for i in search_res:
            articles = articles + "<h3>%i: "%(search_res.index(i)+1) + str(*i) + "</h3><br>"
        return HttpResponse("<h2>This is the result of search</h2> %s" % articles)
    except:
        return HttpResponse("No such articles")

def archive(request):
    return HttpResponse("This are the articles for the last N years/months/days <br>")

def showComments(request, article_id):
    return HttpResponse("This is all comments to this article %i" % article_id)

myDjangoProject/myFirstApp/templates/myFirstApp/article.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p><h3><a href="{% url 'myFirstApp:index' %}"> Home </a></h3>

    <h2>{{ article.article_name }}</h2>
    <ul>
        <li> {{article.article_text}} </li>

    </ul>
    <!-- {{ article }} -->
  </body>
</html>

myDjangoProject/myFirstApp/templates/myFirstApp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <!-- If latest_articles that come from views/context are not empty, then we
          some operations -->
    {% if latest_articles %}
    <ul>
      <!-- running through all articles that we have in our table/model Article -->
      {% for article in latest_articles %}

      <!-- Hardcoded url referencing -->
      <!-- <li><a href="{/article/{{article.id}}/}"> {{article.article_text}}</a></li> -->

      <!-- Accessing the views using its name in the path function (you can delete myFirstApp here)-->
      <!-- <li><a href="{% url 'myFirstApp:article' article.id %}"> {{article.article_text}}</a></li> -->

      <!-- Finally define the name of the app in the urls.py of app and then access its views by name -->
      <li><a href="{% url 'myFirstApp:article' article.id %}"> {{article.article_text}}</a></li>

      {% endfor %}
    </ul>
    {% else %}
      <p> "No articles available" </p>
    {% endif %}

  </body>
</html>